export enum BusinessSetupStatus {
  WELCOME = 'WELCOME',
  BUSINESS_ANALYSIS = 'BUSINESS_ANALYSIS',
  SALES_FUNNEL_DESIGN = 'SALES_FUNNEL_DESIGN',
  AGENT_SETUP = 'AGENT_SETUP',
  WORKFLOW_CREATION = 'WORKFLOW_CREATION',
  TEAM_ASSIGNMENT = 'TEAM_ASSIGNMENT',
  TESTING_OPTIMIZATION = 'TESTING_OPTIMIZATION',
  COMPLETED = 'COMPLETED',
}
